accumulate_grad_batches: 1
amp_level: O1
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 1000
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: ./data
default_root_dir: null
deterministic: false
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
gpus: 1
gradient_clip_val: 0
learning_rate: 0.01
log_gpu_memory: null
log_save_interval: 100
logger: true
max_epochs: 100
max_steps: null
min_epochs: 1
min_steps: null
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_tpu_cores: null
overfit_pct: 0.0
precision: 32
print_nan_grads: false
process_position: 0
profiler: null
progress_bar_callback: true
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 10
terminate_on_nan: false
test_percent_check: 1.0
track_grad_norm: -1
train_percent_check: 1.0
truncated_bptt_steps: null
val_check_interval: 1.0
val_percent_check: 1.0
weights_save_path: null
weights_summary: full
